name: Terraform
description: Runs Terraform stuff
inputs:
  terraform-version:
    description: Terraform version
    default: '0.15.5'
runs:
  using: composite
  steps:
    - run: |
        curl -o terraform.zip https://releases.hashicorp.com/terraform/${{inputs.terraform-version}}/terraform_${{inputs.terraform-version}}_linux_amd64.zip 
        unzip terraform.zip
        chmod +x terraform
        sudo mv terraform /usr/local/bin/setup-terraform.sh
      shell: bash
    - run: terraform version
      shell: bash
    - run: ${{ github.action_path }}/bin/provision-workspace.sh
      shell: bash
      env:
        TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
