name: Terraform
description: Runs terraoform stuff
runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.25
    - run: terraform version
